#!/bin/bash
# scripts/verify-output.sh — verify the portable-markdown contract for files
# produced by the `llm-wiki-markdown` skill.
#
# Every file under <vault>/output/ MUST:
#   - have YAML frontmatter that opens and closes with `---`
#   - declare `generated_by: llm-wiki-markdown`
#   - declare a `source_query:` field
#   - declare a `generated_at: YYYY-MM-DD` field
#   - declare a `sources:` field (inline `[]` or block list of `[[wikilinks]]`)
#   - contain no `[[wikilinks]]` outside the frontmatter and the trailing
#     attribution line (the body must be portable markdown)
#
# Exit codes:
#   0  every file under <vault>/output/ conforms (or the directory is empty)
#   1  one or more files violate the contract
#   2  invocation error (missing argument, vault directory not found)
#
# Usage:
#   scripts/verify-output.sh <vault-root>
#
# The vault root is the directory that contains `output/`. The skill writes
# to `<vault>/output/<slug>.md`; this script audits that subtree only.

set -uo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <vault-root>" >&2
  exit 2
fi

VAULT_ROOT="$1"

if [ ! -d "$VAULT_ROOT" ]; then
  echo "verify-output: vault root not found: $VAULT_ROOT" >&2
  exit 2
fi

OUTPUT_DIR="$VAULT_ROOT/output"

# Empty or absent output/ is a clean state — the skill may not have run yet.
if [ ! -d "$OUTPUT_DIR" ]; then
  exit 0
fi

violations=0

# Iterate over every markdown file directly inside output/. Subdirectories
# are not part of the contract today, so we leave them alone.
while IFS= read -r f; do
  errors=()

  # Frontmatter must open on line 1 with `---`.
  first_line=$(head -n 1 "$f")
  if [ "$first_line" != "---" ]; then
    errors+=("missing opening ---")
  fi

  # Frontmatter must close. Capture the closing line number for the
  # body-scope wikilink check below.
  fm_end=$(awk 'NR>1 && /^---$/ { print NR; exit }' "$f")
  if [ -z "$fm_end" ]; then
    errors+=("missing closing ---")
    fm_end=0
  fi

  # Required frontmatter fields. We grep within the frontmatter range only
  # so a stray match in the body cannot mask a missing field.
  fm_block=$(awk -v end="$fm_end" 'NR<=end' "$f")

  case "$fm_block" in
    *$'\ngenerated_by: llm-wiki-markdown'*) ;;
    *$'\ngenerated_by: "llm-wiki-markdown"'*) ;;
    *) errors+=("missing or wrong generated_by field") ;;
  esac

  case "$fm_block" in
    *$'\nsource_query:'*) ;;
    *) errors+=("missing source_query field") ;;
  esac

  if ! printf '%s\n' "$fm_block" | grep -qE '^generated_at:[[:space:]]+[0-9]{4}-[0-9]{2}-[0-9]{2}'; then
    errors+=("missing or malformed generated_at (expected YYYY-MM-DD)")
  fi

  case "$fm_block" in
    *$'\nsources:'*) ;;
    *) errors+=("missing sources field") ;;
  esac

  # Body must be portable markdown — no [[wikilinks]] except in the
  # trailing attribution line. We allow a single trailing line that begins
  # with `*Generated by` (the skill's attribution convention) to carry
  # `[[wikilinks]]` for provenance.
  body_violations=$(awk -v start="$((fm_end + 1))" '
    NR < start { next }
    /^\*Generated by / { next }
    /\[\[[^]]+\]\]/    { print NR ": " $0 }
  ' "$f")

  if [ -n "$body_violations" ]; then
    while IFS= read -r line; do
      errors+=("body wikilink at $line")
    done <<<"$body_violations"
  fi

  if [ "${#errors[@]}" -gt 0 ]; then
    echo "FAIL: $f"
    for e in "${errors[@]}"; do
      echo "    $e"
    done
    violations=$((violations + 1))
  fi
done < <(find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.md')

if [ "$violations" -gt 0 ]; then
  echo "verify-output: $violations file(s) violate the portable-markdown contract" >&2
  exit 1
fi

exit 0
